version: "2"

services:
  server:
    build: ./server
    ports:
      - 3000:3000
    working_dir: /code
    volumes:
      - ./server:/code
      - /code/node_modules
    command: npm run start:dev
  client:
    build: ./client
    ports:
      - 3001:3000
    working_dir: /code
    volumes:
      - ./client:/code
      - /code/node_modules
    command: npm run start