version: "3"

services:
  server:
    build: .
    ports:
      - 3000:3000
    working_dir: /code
    volumes:
      - ./server:/code
    command: npm run start:dev
  client:
    build: .
    ports:
      - 3001:3000
    working_dir: /code
    volumes:
      - ./client:/code
    command: npm run start